import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  fr: {
    // Common
    'app.title': 'Suite de Gestion IT',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.add': 'Ajouter',
    'common.register': 'S\'inscrire',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.import': 'Importer',
    'common.export': 'Exporter',
    'common.select': 'Sélectionner',
    'common.selectAll': 'Tout sélectionner',
    'common.clear': 'Effacer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.details': 'Détails',
    'common.asset': 'Équipement',
    'common.language': 'Langue',
    'common.selectLanguage': 'Sélectionner la langue',
    'common.allYears': 'Toutes les années',
    'common.typeYear': 'Tapez l\'année...',
    'common.or': 'ou',
    'common.searchPlaceholder': 'Rechercher des équipements, tâches, projets...',
    'common.administrator': 'Administrateur',
    'common.user': 'Utilisateur',
    
    // Import
    'import.instructions': 'Instructions d\'importation',
    'import.instruction1': 'Assurez-vous que votre fichier Excel a des en-têtes dans la première ligne',
    'import.instruction2': 'Les noms de colonnes seront automatiquement mappés aux champs de base de données',
    'import.instruction3': 'Langues supportées : Anglais, Français, Arabe',
    'import.instruction4': 'Prévisualisez vos données avant l\'importation',
    'import.previewing': 'Prévisualisation...',
    'import.previewImport': 'Prévisualiser l\'importation',
    
    // IT Assets
    'itAssets.title': 'Équipements IT',
    'itAssets.subtitle': 'Gérez vos équipements informatiques et périphériques',
    'itAssets.addAsset': 'Ajouter un équipement',
    'itAssets.searchPlaceholder': 'Rechercher des équipements...',
    'itAssets.selectAll': 'Tout sélectionner',
    'itAssets.clearSelection': 'Effacer la sélection',
    'itAssets.bulkDelete': 'Supprimer ({count})',
    'itAssets.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer {count} équipement(s) ?',
    'itAssets.deleteError': 'Erreur lors de la suppression des équipements',
    'itAssets.selectMode': 'Mode sélection',
    'itAssets.exitSelectMode': 'Quitter le mode sélection',
    'itAssets.noAssetsFound': 'Aucun équipement trouvé',
    'itAssets.tryAdjustingFilters': 'Essayez d\'ajuster vos filtres de recherche',
    'itAssets.addFirstAsset': 'Ajouter le premier équipement',
    'itAssets.deviceName': 'Nom de l\'équipement',
    'itAssets.deviceType': 'Type d\'équipement',
    'itAssets.brand': 'Marque',
    'itAssets.model': 'Modèle',
    'itAssets.serialNumber': 'Numéro de série',
    'itAssets.macAddress': 'Adresse MAC',
    'itAssets.ipAddress': 'Adresse IP',
    'itAssets.location': 'Localisation',
    'itAssets.assignedTo': 'Assigné à',
    'itAssets.purchaseDate': 'Date d\'achat',
    'itAssets.warrantyExpiry': 'Expiration de garantie',
    'itAssets.notes': 'Notes',
    'itAssets.addNewAsset': 'Ajouter un nouvel équipement',
    'itAssets.editAsset': 'Modifier l\'équipement',
    'itAssets.assetDetails': 'Détails de l\'équipement',
    'itAssets.updateAsset': 'Mettre à jour l\'équipement',
    'itAssets.close': 'Fermer',
    'itAssets.allDeviceTypes': 'Tous les types d\'équipements',
    'itAssets.allStatus': 'Tous les statuts',
    'itAssets.of': 'de',
    'itAssets.assets': 'équipements',
    
    // Telecom Assets
    'telecomAssets.title': 'Équipements Télécom',
    'telecomAssets.subtitle': 'Gérez vos équipements de télécommunication',
    'telecomAssets.addAsset': 'Ajouter un équipement',
    'telecomAssets.searchPlaceholder': 'Rechercher des équipements...',
    'telecomAssets.selectAll': 'Tout sélectionner',
    'telecomAssets.clearSelection': 'Effacer la sélection',
    'telecomAssets.bulkDelete': 'Supprimer ({count})',
    'telecomAssets.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer {count} équipement(s) ?',
    'telecomAssets.deleteError': 'Erreur lors de la suppression des équipements',
    'telecomAssets.selectMode': 'Mode sélection',
    'telecomAssets.exitSelectMode': 'Quitter le mode sélection',
    'telecomAssets.noAssetsFound': 'Aucun équipement trouvé',
    'telecomAssets.tryAdjustingFilters': 'Essayez d\'ajuster vos filtres de recherche',
    'telecomAssets.addFirstAsset': 'Ajouter le premier équipement',
    'telecomAssets.provider': 'Fournisseur',
    'telecomAssets.simNumber': 'Numéro SIM',
    'telecomAssets.simOwner': 'Propriétaire SIM',
    'telecomAssets.subscriptionType': 'Type d\'abonnement',
    'telecomAssets.phoneNumber': 'Numéro de téléphone',
    'telecomAssets.dataPlan': 'Forfait données',
    'telecomAssets.pinCode': 'Code PIN',
    'telecomAssets.pukCode': 'Code PUK',
    'telecomAssets.zone': 'Zone',
    'telecomAssets.company': 'Entreprise',
    'telecomAssets.position': 'Poste/Activité',
    'telecomAssets.phoneName': 'Nom du téléphone',
    'telecomAssets.activity': 'Activité',
    'telecomAssets.addNewAsset': 'Ajouter un nouvel équipement',
    'telecomAssets.editAsset': 'Modifier l\'équipement',
    'telecomAssets.assetDetails': 'Détails de l\'équipement',
    'telecomAssets.updateAsset': 'Mettre à jour l\'équipement',
    'telecomAssets.close': 'Fermer',
    'telecomAssets.allProviders': 'Tous les fournisseurs',
    'telecomAssets.allStatus': 'Tous les statuts',
    'telecomAssets.of': 'de',
    'telecomAssets.assets': 'équipements',
    'telecomAssets.simInformation': 'Informations SIM',
    'telecomAssets.organizationDetails': 'Détails de l\'organisation',
    
    // Device Types
    'deviceTypes.laptop': 'Ordinateur portable',
    'deviceTypes.desktop': 'Ordinateur de bureau',
    'deviceTypes.mouse': 'Souris',
    'deviceTypes.keyboard': 'Clavier',
    'deviceTypes.headphones': 'Casque',
    'deviceTypes.monitor': 'Écran',
    'deviceTypes.server': 'Serveur',
    'deviceTypes.printer': 'Imprimante',
    
    // Fields
    'fields.deviceType': 'Type d\'équipement',
    'fields.ownerName': 'Propriétaire',
    'fields.department': 'Département',
    'fields.zone': 'Zone/Emplacement',
    'fields.activity': 'Poste/Activité',
    'fields.serialNumber': 'Numéro de série',
    'fields.ticketNumber': 'Numéro de ticket',
    'fields.model': 'Modèle',
    'fields.brand': 'Marque',
    'fields.date': 'Date',
    'fields.status': 'Statut',
    'fields.ram': 'RAM (GB)',
    'fields.disk': 'Disque (GB)',
    'fields.processor': 'Processeur',
    'fields.os': 'Système d\'exploitation',
    'fields.peripheralType': 'Type de périphérique',
    'fields.connectionType': 'Type de connexion',
    'fields.location': 'Localisation',
    'fields.macAddress': 'Adresse MAC',
    'fields.ipAddress': 'Adresse IP',
    'fields.purchaseDate': 'Date d\'achat',
    'fields.warrantyExpiry': 'Expiration de garantie',
    'fields.notes': 'Notes',
    'fields.deviceName': 'Nom de l\'équipement',
    'fields.type': 'Type',
    'fields.assignedUser': 'Utilisateur assigné',
    'fields.manufacturer': 'Fabricant',
    'fields.lastSeen': 'Dernière vue',
    'fields.antivirusStatus': 'Statut antivirus',
    'fields.updateStatus': 'Statut des mises à jour',
    'fields.year': 'Année',
    'fields.name': 'Nom',
    'fields.imei': 'IMEI',
    'fields.storage': 'Stockage (GB)',
    'fields.hostname': 'Nom d\'hôte',
    'fields.company': 'Entreprise',
    'fields.description': 'Description',
    'fields.priority': 'Priorité',
    'fields.startDate': 'Date de début',
    'fields.endDate': 'Date de fin',
    'fields.budget': 'Budget',
    'fields.manager': 'Gestionnaire',
    'export.format': 'Format d\'exportation',
    'export.theme': 'Style de thème',
    
    // Dashboard
    'dashboard.totalDevices': 'Total des appareils',
    'dashboard.totalDevicesSubtitle': 'Tous les appareils enregistrés',
    'dashboard.activeDevices': 'Appareils actifs',
    'dashboard.activeDevicesSubtitle': 'Actuellement en ligne',
    'dashboard.totalTasks': 'Total des tâches',
    'dashboard.totalTasksSubtitle': 'Toutes les tâches assignées',
    'dashboard.completedTasks': 'Tâches terminées',
    'dashboard.completedTasksSubtitle': 'Terminées avec succès',
    'dashboard.activeProjects': 'Projets actifs',
    'dashboard.activeProjectsSubtitle': 'Actuellement en cours',
    'dashboard.totalUsers': 'Total des utilisateurs',
    'dashboard.totalUsersSubtitle': 'Utilisateurs enregistrés',
    'dashboard.deviceStatus.active': 'Actif',
    'dashboard.deviceStatus.inactive': 'Inactif',
    'dashboard.deviceStatus.maintenance': 'Maintenance',
    'dashboard.charts.cpu': 'CPU %',
    'dashboard.charts.memory': 'Mémoire %',
    'dashboard.charts.disk': 'Disque %',
    
    // Status
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.maintenance': 'Maintenance',
    'status.retired': 'Retiré',
    
    // AI Import
    'aiImport.title': 'Import IA',
    'aiImport.subtitle': 'Importez des équipements avec l\'intelligence artificielle',
    'aiImport.selectFile': 'Sélectionner un fichier',
    'aiImport.preview': 'Aperçu',
    'aiImport.import': 'Importer',
    'aiImport.success': 'Import réussi',
    'aiImport.error': 'Erreur d\'import',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.clearAll': 'Tout effacer',
    'notifications.noNotifications': 'Aucune notification',
    'notifications.markAsRead': 'Marquer comme lu',
    'notifications.delete': 'Supprimer',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.systemStatus': 'État du système',
    'dashboard.performance': 'Performance',
    'dashboard.storage': 'Stockage',
    'dashboard.memory': 'Mémoire',
    'dashboard.cpu': 'Processeur',
    
    // Login
    'login.title': 'Connexion',
    'login.subtitle': 'Connectez-vous à votre compte',
    'login.applicationMode': 'Mode d\'application',
    'login.changeMode': 'Changer de mode',
    'login.current': 'Actuel',
    'login.modes.local': 'Local',
    'login.modes.client': 'Client',
    'login.modes.server': 'Serveur',
    'login.modes.cloud': 'Cloud',
    'login.availableServers': 'Serveurs disponibles',
    'login.serverName': 'Nom du serveur',
    'login.serverIP': 'IP du serveur',
    'login.confirmPassword': 'Confirmer le mot de passe',
    'login.email': 'Adresse e-mail',
    'login.password': 'Mot de passe',
    'login.rememberMe': 'Se souvenir de moi',
    'login.forgotPassword': 'Mot de passe oublié ?',
    'login.signIn': 'Se connecter',
    'login.invalidCredentials': 'Identifiants invalides',
    'login.loginError': 'Erreur de connexion',
    'login.enterEmail': 'Entrez votre adresse e-mail',
    'login.enterPassword': 'Entrez votre mot de passe',
    
    // Devices
    'devices.title': 'Appareils',
    'devices.subtitle': 'Gérez vos appareils connectés',
    'devices.addDevice': 'Ajouter un appareil',
    'devices.deviceName': 'Nom de l\'appareil',
    'devices.deviceType': 'Type d\'appareil',
    'devices.status': 'Statut',
    'devices.lastSeen': 'Dernière connexion',
    'devices.actions': 'Actions',
    'devices.noDevices': 'Aucun appareil trouvé',
    'devices.addFirstDevice': 'Ajouter le premier appareil',
    'devices.searchPlaceholder': 'Rechercher des appareils...',
    'devices.allTypes': 'Tous les types',
    'devices.allStatus': 'Tous les statuts',
    'devices.online': 'En ligne',
    'devices.offline': 'Hors ligne',
    'devices.unknown': 'Inconnu',
    
    // Tasks
    'tasks.title': 'Tâches',
    'tasks.subtitle': 'Gérez vos tâches et projets',
    'tasks.addTask': 'Ajouter une tâche',
    'tasks.taskName': 'Nom de la tâche',
    'tasks.description': 'Description',
    'tasks.priority': 'Priorité',
    'tasks.status': 'Statut',
    'tasks.assignee': 'Assigné à',
    'tasks.dueDate': 'Date d\'échéance',
    'tasks.createdDate': 'Date de création',
    'tasks.noTasks': 'Aucune tâche trouvée',
    'tasks.addFirstTask': 'Ajouter la première tâche',
    'tasks.searchPlaceholder': 'Rechercher des tâches...',
    'tasks.high': 'Élevée',
    'tasks.medium': 'Moyenne',
    'tasks.low': 'Faible',
    'tasks.todo': 'À faire',
    'tasks.inProgress': 'En cours',
    'tasks.completed': 'Terminée',
    'tasks.cancelled': 'Annulée',
    
    // Projects
    'projects.title': 'Projets',
    'projects.subtitle': 'Gérez vos projets',
    'projects.addProject': 'Ajouter un projet',
    'projects.projectName': 'Nom du projet',
    'projects.description': 'Description',
    'projects.status': 'Statut',
    'projects.manager': 'Gestionnaire',
    'projects.startDate': 'Date de début',
    'projects.endDate': 'Date de fin',
    'projects.progress': 'Progression',
    'projects.noProjects': 'Aucun projet trouvé',
    'projects.addFirstProject': 'Ajouter le premier projet',
    'projects.searchPlaceholder': 'Rechercher des projets...',
    'projects.planning': 'Planification',
    'projects.active': 'Actif',
    'projects.completed': 'Terminé',
    'projects.onHold': 'En attente',
    'projects.cancelled': 'Annulé',
    
    // Users
    'users.title': 'Utilisateurs',
    'users.subtitle': 'Gérez les utilisateurs du système',
    'users.addUser': 'Ajouter un utilisateur',
    'users.username': 'Nom d\'utilisateur',
    'users.email': 'E-mail',
    'users.firstName': 'Prénom',
    'users.lastName': 'Nom',
    'users.role': 'Rôle',
    'users.department': 'Département',
    'users.status': 'Statut',
    'users.lastLogin': 'Dernière connexion',
    'users.createdDate': 'Date de création',
    'users.noUsers': 'Aucun utilisateur trouvé',
    'users.addFirstUser': 'Ajouter le premier utilisateur',
    'users.searchPlaceholder': 'Rechercher des utilisateurs...',
    'users.admin': 'Administrateur',
    'users.user': 'Utilisateur',
    'users.manager': 'Gestionnaire',
    'users.active': 'Actif',
    'users.inactive': 'Inactif',
    'users.suspended': 'Suspendu',
    
    // System Info
    'system.title': 'Informations système',
    'system.subtitle': 'Surveillez les performances de votre système',
    'system.overview': 'Aperçu',
    'system.hardware': 'Matériel',
    'system.software': 'Logiciel',
    'system.network': 'Réseau',
    'system.storage': 'Stockage',
    'system.memory': 'Mémoire',
    'system.cpu': 'Processeur',
    'system.uptime': 'Temps de fonctionnement',
    'system.version': 'Version',
    'system.platform': 'Plateforme',
    'system.architecture': 'Architecture',
    'system.totalMemory': 'Mémoire totale',
    'system.freeMemory': 'Mémoire libre',
    'system.usedMemory': 'Mémoire utilisée',
    'system.cpuUsage': 'Utilisation CPU',
    'system.diskSpace': 'Espace disque',
    'system.networkInterfaces': 'Interfaces réseau',
    'system.loadAverage': 'Charge moyenne',
    
    // AI
    'ai.title': 'Assistant IA',
    'ai.subtitle': 'Utilisez l\'intelligence artificielle pour automatiser vos tâches',
    'ai.chat': 'Chat IA',
    'ai.askQuestion': 'Posez une question...',
    'ai.send': 'Envoyer',
    'ai.clear': 'Effacer',
    'ai.import': 'Import IA',
    'ai.export': 'Export IA',
    'ai.analyze': 'Analyser',
    'ai.generate': 'Générer',
    'ai.recommendations': 'Recommandations',
    'ai.insights': 'Insights',
    'ai.noData': 'Aucune donnée disponible',
    'ai.loading': 'Chargement...',
    'ai.error': 'Erreur IA',
    'ai.success': 'Succès IA',
    
    // Sidebar
    'sidebar.dashboard': 'Tableau de bord',
    'sidebar.devices': 'Appareils',
    'sidebar.itAssets': 'Équipements IT',
    'sidebar.telecomAssets': 'Équipements Télécom',
    'sidebar.tasks': 'Tâches',
    'sidebar.projects': 'Projets',
    'sidebar.users': 'Utilisateurs',
    'sidebar.system': 'Système',
    'sidebar.ai': 'IA',
    'sidebar.settings': 'Paramètres',
    'sidebar.logout': 'Déconnexion',
    
    // Header
    'header.notifications': 'Notifications',
    'header.profile': 'Profil',
    'header.settings': 'Paramètres',
    'header.help': 'Aide',
    'header.support': 'Support',
    
    // Common Actions
    'actions.view': 'Voir',
    'actions.edit': 'Modifier',
    'actions.delete': 'Supprimer',
    'actions.save': 'Enregistrer',
    'actions.cancel': 'Annuler',
    'actions.close': 'Fermer',
    'actions.back': 'Retour',
    'actions.next': 'Suivant',
    'actions.previous': 'Précédent',
    'actions.refresh': 'Actualiser',
    'actions.loading': 'Chargement...',
    'actions.error': 'Erreur',
    'actions.success': 'Succès',
    'actions.warning': 'Attention',
    'actions.info': 'Information',
    'actions.confirm': 'Confirmer',
    'actions.yes': 'Oui',
    'actions.no': 'Non',
    'actions.ok': 'OK',
    'actions.apply': 'Appliquer',
    'actions.reset': 'Réinitialiser',
    'actions.submit': 'Soumettre',
    'actions.upload': 'Télécharger',
    'actions.download': 'Télécharger',
    'actions.print': 'Imprimer',
    'actions.share': 'Partager',
    'actions.copy': 'Copier',
    'actions.paste': 'Coller',
    'actions.cut': 'Couper',
    'actions.undo': 'Annuler',
    'actions.redo': 'Refaire',
  },
  es: {
    // Common
    'app.title': 'Suite de Gestión IT',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.add': 'Agregar',
    'common.register': 'Registrarse',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.import': 'Importar',
    'common.export': 'Exportar',
    'common.select': 'Seleccionar',
    'common.selectAll': 'Seleccionar todo',
    'common.clear': 'Limpiar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.details': 'Detalles',
    'common.asset': 'Equipo',
    'common.language': 'Idioma',
    'common.selectLanguage': 'Seleccionar idioma',
    'common.allYears': 'Todos los años',
    'common.typeYear': 'Escribir año...',
    'common.or': 'o',
    'common.searchPlaceholder': 'Buscar equipos, tareas, proyectos...',
    'common.administrator': 'Administrador',
    'common.user': 'Usuario',
    
    // Import
    'import.instructions': 'Instrucciones de importación',
    'import.instruction1': 'Asegúrese de que su archivo Excel tenga encabezados en la primera fila',
    'import.instruction2': 'Los nombres de columna se mapearán automáticamente a los campos de base de datos',
    'import.instruction3': 'Idiomas soportados: Inglés, Francés, Árabe',
    'import.instruction4': 'Vea una vista previa de sus datos antes de importar',
    'import.previewing': 'Vista previa...',
    'import.previewImport': 'Vista previa de importación',
    
    // IT Assets
    'itAssets.title': 'Equipos IT',
    'itAssets.subtitle': 'Gestiona tus equipos informáticos y periféricos',
    'itAssets.addAsset': 'Agregar equipo',
    'itAssets.searchPlaceholder': 'Buscar equipos...',
    'itAssets.selectAll': 'Seleccionar todo',
    'itAssets.clearSelection': 'Limpiar selección',
    'itAssets.bulkDelete': 'Eliminar ({count})',
    'itAssets.deleteConfirm': '¿Estás seguro de que quieres eliminar {count} equipo(s)?',
    'itAssets.deleteError': 'Error al eliminar los equipos',
    'itAssets.selectMode': 'Modo selección',
    'itAssets.exitSelectMode': 'Salir del modo selección',
    'itAssets.noAssetsFound': 'No se encontraron equipos',
    'itAssets.tryAdjustingFilters': 'Intenta ajustar tus filtros de búsqueda',
    'itAssets.addFirstAsset': 'Agregar el primer equipo',
    'itAssets.deviceName': 'Nombre del equipo',
    'itAssets.deviceType': 'Tipo de equipo',
    'itAssets.brand': 'Marca',
    'itAssets.model': 'Modelo',
    'itAssets.serialNumber': 'Número de serie',
    'itAssets.macAddress': 'Dirección MAC',
    'itAssets.ipAddress': 'Dirección IP',
    'itAssets.location': 'Ubicación',
    'itAssets.assignedTo': 'Asignado a',
    'itAssets.purchaseDate': 'Fecha de compra',
    'itAssets.warrantyExpiry': 'Vencimiento de garantía',
    'itAssets.notes': 'Notas',
    'itAssets.addNewAsset': 'Agregar nuevo equipo',
    'itAssets.editAsset': 'Editar equipo',
    'itAssets.assetDetails': 'Detalles del equipo',
    'itAssets.updateAsset': 'Actualizar equipo',
    'itAssets.close': 'Cerrar',
    'itAssets.allDeviceTypes': 'Todos los tipos de equipos',
    'itAssets.allStatus': 'Todos los estados',
    'itAssets.of': 'de',
    'itAssets.assets': 'equipos',
    
    // Telecom Assets
    'telecomAssets.title': 'Equipos Telecom',
    'telecomAssets.subtitle': 'Gestiona tus equipos de telecomunicaciones',
    'telecomAssets.addAsset': 'Agregar equipo',
    'telecomAssets.searchPlaceholder': 'Buscar equipos...',
    'telecomAssets.selectAll': 'Seleccionar todo',
    'telecomAssets.clearSelection': 'Limpiar selección',
    'telecomAssets.bulkDelete': 'Eliminar ({count})',
    'telecomAssets.deleteConfirm': '¿Estás seguro de que quieres eliminar {count} equipo(s)?',
    'telecomAssets.deleteError': 'Error al eliminar los equipos',
    'telecomAssets.selectMode': 'Modo selección',
    'telecomAssets.exitSelectMode': 'Salir del modo selección',
    'telecomAssets.noAssetsFound': 'No se encontraron equipos',
    'telecomAssets.tryAdjustingFilters': 'Intenta ajustar tus filtros de búsqueda',
    'telecomAssets.addFirstAsset': 'Agregar el primer equipo',
    'telecomAssets.provider': 'Proveedor',
    'telecomAssets.simNumber': 'Número SIM',
    'telecomAssets.simOwner': 'Propietario SIM',
    'telecomAssets.subscriptionType': 'Tipo de suscripción',
    'telecomAssets.phoneNumber': 'Número de teléfono',
    'telecomAssets.dataPlan': 'Plan de datos',
    'telecomAssets.pinCode': 'Código PIN',
    'telecomAssets.pukCode': 'Código PUK',
    'telecomAssets.zone': 'Zona',
    'telecomAssets.company': 'Empresa',
    'telecomAssets.position': 'Puesto/Actividad',
    'telecomAssets.phoneName': 'Nombre del teléfono',
    'telecomAssets.activity': 'Actividad',
    'telecomAssets.addNewAsset': 'Agregar nuevo equipo',
    'telecomAssets.editAsset': 'Editar equipo',
    'telecomAssets.assetDetails': 'Detalles del equipo',
    'telecomAssets.updateAsset': 'Actualizar equipo',
    'telecomAssets.close': 'Cerrar',
    'telecomAssets.allProviders': 'Todos los proveedores',
    'telecomAssets.allStatus': 'Todos los estados',
    'telecomAssets.of': 'de',
    'telecomAssets.assets': 'equipos',
    'telecomAssets.simInformation': 'Información SIM',
    'telecomAssets.organizationDetails': 'Detalles de la organización',
    
    // Device Types
    'deviceTypes.laptop': 'Portátil',
    'deviceTypes.desktop': 'Escritorio',
    'deviceTypes.mouse': 'Ratón',
    'deviceTypes.keyboard': 'Teclado',
    'deviceTypes.headphones': 'Auriculares',
    'deviceTypes.monitor': 'Monitor',
    'deviceTypes.server': 'Servidor',
    'deviceTypes.printer': 'Impresora',
    
    // Fields
    'fields.deviceType': 'Tipo de equipo',
    'fields.ownerName': 'Propietario',
    'fields.department': 'Departamento',
    'fields.zone': 'Zona/Ubicación',
    'fields.activity': 'Puesto/Actividad',
    'fields.serialNumber': 'Número de serie',
    'fields.ticketNumber': 'Número de ticket',
    'fields.model': 'Modelo',
    'fields.brand': 'Marca',
    'fields.date': 'Fecha',
    'fields.status': 'Estado',
    'fields.ram': 'RAM (GB)',
    'fields.disk': 'Disco (GB)',
    'fields.processor': 'Procesador',
    'fields.os': 'Sistema operativo',
    'fields.peripheralType': 'Tipo de periférico',
    'fields.connectionType': 'Tipo de conexión',
    'fields.location': 'Ubicación',
    'fields.macAddress': 'Dirección MAC',
    'fields.ipAddress': 'Dirección IP',
    'fields.purchaseDate': 'Fecha de compra',
    'fields.warrantyExpiry': 'Vencimiento de garantía',
    'fields.notes': 'Notas',
    'fields.deviceName': 'Nombre del equipo',
    'fields.type': 'Tipo',
    'fields.assignedUser': 'Usuario asignado',
    'fields.manufacturer': 'Fabricante',
    'fields.lastSeen': 'Última vista',
    'fields.antivirusStatus': 'Estado del antivirus',
    'fields.updateStatus': 'Estado de actualizaciones',
    'fields.year': 'Año',
    'fields.name': 'Nombre',
    'fields.imei': 'IMEI',
    'fields.storage': 'Almacenamiento (GB)',
    'fields.hostname': 'Nombre de host',
    'fields.company': 'Empresa',
    'fields.description': 'Descripción',
    'fields.priority': 'Prioridad',
    'fields.startDate': 'Fecha de inicio',
    'fields.endDate': 'Fecha de fin',
    'fields.budget': 'Presupuesto',
    'fields.manager': 'Gerente',
    'export.format': 'Formato de exportación',
    'export.theme': 'Estilo de tema',
    
    // Dashboard
    'dashboard.totalDevices': 'Total de dispositivos',
    'dashboard.totalDevicesSubtitle': 'Todos los dispositivos registrados',
    'dashboard.activeDevices': 'Dispositivos activos',
    'dashboard.activeDevicesSubtitle': 'Actualmente en línea',
    'dashboard.totalTasks': 'Total de tareas',
    'dashboard.totalTasksSubtitle': 'Todas las tareas asignadas',
    'dashboard.completedTasks': 'Tareas completadas',
    'dashboard.completedTasksSubtitle': 'Completadas exitosamente',
    'dashboard.activeProjects': 'Proyectos activos',
    'dashboard.activeProjectsSubtitle': 'Actualmente en progreso',
    'dashboard.totalUsers': 'Total de usuarios',
    'dashboard.totalUsersSubtitle': 'Usuarios registrados',
    'dashboard.deviceStatus.active': 'Activo',
    'dashboard.deviceStatus.inactive': 'Inactivo',
    'dashboard.deviceStatus.maintenance': 'Mantenimiento',
    'dashboard.charts.cpu': 'CPU %',
    'dashboard.charts.memory': 'Memoria %',
    'dashboard.charts.disk': 'Disco %',
    
    // Status
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.maintenance': 'Mantenimiento',
    'status.retired': 'Retirado',
    
    // AI Import
    'aiImport.title': 'Importar IA',
    'aiImport.subtitle': 'Importa equipos con inteligencia artificial',
    'aiImport.selectFile': 'Seleccionar archivo',
    'aiImport.preview': 'Vista previa',
    'aiImport.import': 'Importar',
    'aiImport.success': 'Importación exitosa',
    'aiImport.error': 'Error de importación',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.markAllRead': 'Marcar todo como leído',
    'notifications.clearAll': 'Limpiar todo',
    'notifications.noNotifications': 'Sin notificaciones',
    'notifications.markAsRead': 'Marcar como leído',
    'notifications.delete': 'Eliminar',
    
    // Dashboard
    'dashboard.title': 'Panel de control',
    'dashboard.quickActions': 'Acciones rápidas',
    'dashboard.systemStatus': 'Estado del sistema',
    'dashboard.performance': 'Rendimiento',
    'dashboard.storage': 'Almacenamiento',
    'dashboard.memory': 'Memoria',
    'dashboard.cpu': 'Procesador',
    
    // Login
    'login.title': 'Iniciar sesión',
    'login.subtitle': 'Inicia sesión en tu cuenta',
    'login.applicationMode': 'Modo de aplicación',
    'login.changeMode': 'Cambiar modo',
    'login.current': 'Actual',
    'login.modes.local': 'Local',
    'login.modes.client': 'Cliente',
    'login.modes.server': 'Servidor',
    'login.modes.cloud': 'Nube',
    'login.availableServers': 'Servidores disponibles',
    'login.serverName': 'Nombre del servidor',
    'login.serverIP': 'IP del servidor',
    'login.confirmPassword': 'Confirmar contraseña',
    'login.email': 'Dirección de correo',
    'login.password': 'Contraseña',
    'login.rememberMe': 'Recordarme',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.signIn': 'Iniciar sesión',
    'login.invalidCredentials': 'Credenciales inválidas',
    'login.loginError': 'Error de inicio de sesión',
    'login.enterEmail': 'Ingresa tu dirección de correo',
    'login.enterPassword': 'Ingresa tu contraseña',
    
    // Devices
    'devices.title': 'Dispositivos',
    'devices.subtitle': 'Gestiona tus dispositivos conectados',
    'devices.addDevice': 'Agregar dispositivo',
    'devices.deviceName': 'Nombre del dispositivo',
    'devices.deviceType': 'Tipo de dispositivo',
    'devices.status': 'Estado',
    'devices.lastSeen': 'Última conexión',
    'devices.actions': 'Acciones',
    'devices.noDevices': 'No se encontraron dispositivos',
    'devices.addFirstDevice': 'Agregar el primer dispositivo',
    'devices.searchPlaceholder': 'Buscar dispositivos...',
    'devices.allTypes': 'Todos los tipos',
    'devices.allStatus': 'Todos los estados',
    'devices.online': 'En línea',
    'devices.offline': 'Desconectado',
    'devices.unknown': 'Desconocido',
    
    // Tasks
    'tasks.title': 'Tareas',
    'tasks.subtitle': 'Gestiona tus tareas y proyectos',
    'tasks.addTask': 'Agregar tarea',
    'tasks.taskName': 'Nombre de la tarea',
    'tasks.description': 'Descripción',
    'tasks.priority': 'Prioridad',
    'tasks.status': 'Estado',
    'tasks.assignee': 'Asignado a',
    'tasks.dueDate': 'Fecha de vencimiento',
    'tasks.createdDate': 'Fecha de creación',
    'tasks.noTasks': 'No se encontraron tareas',
    'tasks.addFirstTask': 'Agregar la primera tarea',
    'tasks.searchPlaceholder': 'Buscar tareas...',
    'tasks.high': 'Alta',
    'tasks.medium': 'Media',
    'tasks.low': 'Baja',
    'tasks.todo': 'Por hacer',
    'tasks.inProgress': 'En progreso',
    'tasks.completed': 'Completada',
    'tasks.cancelled': 'Cancelada',
    
    // Projects
    'projects.title': 'Proyectos',
    'projects.subtitle': 'Gestiona tus proyectos',
    'projects.addProject': 'Agregar proyecto',
    'projects.projectName': 'Nombre del proyecto',
    'projects.description': 'Descripción',
    'projects.status': 'Estado',
    'projects.manager': 'Gerente',
    'projects.startDate': 'Fecha de inicio',
    'projects.endDate': 'Fecha de fin',
    'projects.progress': 'Progreso',
    'projects.noProjects': 'No se encontraron proyectos',
    'projects.addFirstProject': 'Agregar el primer proyecto',
    'projects.searchPlaceholder': 'Buscar proyectos...',
    'projects.planning': 'Planificación',
    'projects.active': 'Activo',
    'projects.completed': 'Completado',
    'projects.onHold': 'En espera',
    'projects.cancelled': 'Cancelado',
    
    // Users
    'users.title': 'Usuarios',
    'users.subtitle': 'Gestiona los usuarios del sistema',
    'users.addUser': 'Agregar usuario',
    'users.username': 'Nombre de usuario',
    'users.email': 'Correo electrónico',
    'users.firstName': 'Nombre',
    'users.lastName': 'Apellido',
    'users.role': 'Rol',
    'users.department': 'Departamento',
    'users.status': 'Estado',
    'users.lastLogin': 'Último inicio de sesión',
    'users.createdDate': 'Fecha de creación',
    'users.noUsers': 'No se encontraron usuarios',
    'users.addFirstUser': 'Agregar el primer usuario',
    'users.searchPlaceholder': 'Buscar usuarios...',
    'users.admin': 'Administrador',
    'users.user': 'Usuario',
    'users.manager': 'Gerente',
    'users.active': 'Activo',
    'users.inactive': 'Inactivo',
    'users.suspended': 'Suspendido',
    
    // System Info
    'system.title': 'Información del sistema',
    'system.subtitle': 'Monitorea el rendimiento de tu sistema',
    'system.overview': 'Resumen',
    'system.hardware': 'Hardware',
    'system.software': 'Software',
    'system.network': 'Red',
    'system.storage': 'Almacenamiento',
    'system.memory': 'Memoria',
    'system.cpu': 'Procesador',
    'system.uptime': 'Tiempo de actividad',
    'system.version': 'Versión',
    'system.platform': 'Plataforma',
    'system.architecture': 'Arquitectura',
    'system.totalMemory': 'Memoria total',
    'system.freeMemory': 'Memoria libre',
    'system.usedMemory': 'Memoria usada',
    'system.cpuUsage': 'Uso de CPU',
    'system.diskSpace': 'Espacio en disco',
    'system.networkInterfaces': 'Interfaces de red',
    'system.loadAverage': 'Carga promedio',
    
    // AI
    'ai.title': 'Asistente IA',
    'ai.subtitle': 'Usa inteligencia artificial para automatizar tus tareas',
    'ai.chat': 'Chat IA',
    'ai.askQuestion': 'Haz una pregunta...',
    'ai.send': 'Enviar',
    'ai.clear': 'Limpiar',
    'ai.import': 'Importar IA',
    'ai.export': 'Exportar IA',
    'ai.analyze': 'Analizar',
    'ai.generate': 'Generar',
    'ai.recommendations': 'Recomendaciones',
    'ai.insights': 'Insights',
    'ai.noData': 'No hay datos disponibles',
    'ai.loading': 'Cargando...',
    'ai.error': 'Error de IA',
    'ai.success': 'Éxito de IA',
    
    // Sidebar
    'sidebar.dashboard': 'Panel de control',
    'sidebar.devices': 'Dispositivos',
    'sidebar.itAssets': 'Equipos IT',
    'sidebar.telecomAssets': 'Equipos Telecom',
    'sidebar.tasks': 'Tareas',
    'sidebar.projects': 'Proyectos',
    'sidebar.users': 'Usuarios',
    'sidebar.system': 'Sistema',
    'sidebar.ai': 'IA',
    'sidebar.settings': 'Configuración',
    'sidebar.logout': 'Cerrar sesión',
    
    // Header
    'header.notifications': 'Notificaciones',
    'header.profile': 'Perfil',
    'header.settings': 'Configuración',
    'header.help': 'Ayuda',
    'header.support': 'Soporte',
    
    // Common Actions
    'actions.view': 'Ver',
    'actions.edit': 'Editar',
    'actions.delete': 'Eliminar',
    'actions.save': 'Guardar',
    'actions.cancel': 'Cancelar',
    'actions.close': 'Cerrar',
    'actions.back': 'Atrás',
    'actions.next': 'Siguiente',
    'actions.previous': 'Anterior',
    'actions.refresh': 'Actualizar',
    'actions.loading': 'Cargando...',
    'actions.error': 'Error',
    'actions.success': 'Éxito',
    'actions.warning': 'Advertencia',
    'actions.info': 'Información',
    'actions.confirm': 'Confirmar',
    'actions.yes': 'Sí',
    'actions.no': 'No',
    'actions.ok': 'OK',
    'actions.apply': 'Aplicar',
    'actions.reset': 'Restablecer',
    'actions.submit': 'Enviar',
    'actions.upload': 'Subir',
    'actions.download': 'Descargar',
    'actions.print': 'Imprimir',
    'actions.share': 'Compartir',
    'actions.copy': 'Copiar',
    'actions.paste': 'Pegar',
    'actions.cut': 'Cortar',
    'actions.undo': 'Deshacer',
    'actions.redo': 'Rehacer',
  },
  en: {
    // Common
    'app.title': 'IT Management Suite',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.register': 'Register',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.select': 'Select',
    'common.selectAll': 'Select All',
    'common.clear': 'Clear',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.details': 'Details',
    'common.asset': 'Asset',
    'common.language': 'Language',
    'common.selectLanguage': 'Select Language',
    'common.allYears': 'All Years',
    'common.typeYear': 'Type year...',
    'common.or': 'or',
    'common.searchPlaceholder': 'Search devices, tasks, projects...',
    'common.administrator': 'Administrator',
    'common.user': 'User',
    
    // Import
    'import.instructions': 'Import Instructions',
    'import.instruction1': 'Ensure your Excel file has headers in the first row',
    'import.instruction2': 'Column names will be automatically mapped to database fields',
    'import.instruction3': 'Supported languages: English, French, Arabic',
    'import.instruction4': 'Preview your data before importing',
    'import.previewing': 'Previewing...',
    'import.previewImport': 'Preview Import',
    
    // IT Assets
    'itAssets.title': 'IT Assets',
    'itAssets.subtitle': 'Manage your IT equipment and peripherals',
    'itAssets.addAsset': 'Add Asset',
    'itAssets.searchPlaceholder': 'Search assets...',
    'itAssets.selectAll': 'Select All',
    'itAssets.clearSelection': 'Clear Selection',
    'itAssets.bulkDelete': 'Delete ({count})',
    'itAssets.deleteConfirm': 'Are you sure you want to delete {count} asset(s)?',
    'itAssets.deleteError': 'Error deleting assets',
    'itAssets.selectMode': 'Select Mode',
    'itAssets.exitSelectMode': 'Exit Select Mode',
    'itAssets.noAssetsFound': 'No assets found',
    'itAssets.tryAdjustingFilters': 'Try adjusting your search or filters',
    'itAssets.addFirstAsset': 'Add First Asset',
    'itAssets.deviceName': 'Device Name',
    'itAssets.deviceType': 'Device Type',
    'itAssets.brand': 'Brand',
    'itAssets.model': 'Model',
    'itAssets.serialNumber': 'Serial Number',
    'itAssets.macAddress': 'MAC Address',
    'itAssets.ipAddress': 'IP Address',
    'itAssets.location': 'Location',
    'itAssets.assignedTo': 'Assigned To',
    'itAssets.purchaseDate': 'Purchase Date',
    'itAssets.warrantyExpiry': 'Warranty Expiry',
    'itAssets.notes': 'Notes',
    'itAssets.addNewAsset': 'Add New Asset',
    'itAssets.editAsset': 'Edit Asset',
    'itAssets.assetDetails': 'Asset Details',
    'itAssets.updateAsset': 'Update Asset',
    'itAssets.close': 'Close',
    'itAssets.allDeviceTypes': 'All Device Types',
    'itAssets.allStatus': 'All Status',
    'itAssets.of': 'of',
    'itAssets.assets': 'assets',
    
    // Telecom Assets
    'telecomAssets.title': 'Telecom Assets',
    'telecomAssets.subtitle': 'Manage your telecommunications equipment',
    'telecomAssets.addAsset': 'Add Asset',
    'telecomAssets.searchPlaceholder': 'Search assets...',
    'telecomAssets.selectAll': 'Select All',
    'telecomAssets.clearSelection': 'Clear Selection',
    'telecomAssets.bulkDelete': 'Delete ({count})',
    'telecomAssets.deleteConfirm': 'Are you sure you want to delete {count} asset(s)?',
    'telecomAssets.deleteError': 'Error deleting assets',
    'telecomAssets.selectMode': 'Select Mode',
    'telecomAssets.exitSelectMode': 'Exit Select Mode',
    'telecomAssets.noAssetsFound': 'No assets found',
    'telecomAssets.tryAdjustingFilters': 'Try adjusting your search or filters',
    'telecomAssets.addFirstAsset': 'Add First Asset',
    'telecomAssets.provider': 'Provider',
    'telecomAssets.simNumber': 'SIM Number',
    'telecomAssets.simOwner': 'SIM Owner',
    'telecomAssets.subscriptionType': 'Subscription Type',
    'telecomAssets.phoneNumber': 'Phone Number',
    'telecomAssets.dataPlan': 'Data Plan',
    'telecomAssets.pinCode': 'PIN Code',
    'telecomAssets.pukCode': 'PUK Code',
    'telecomAssets.zone': 'Zone',
    'telecomAssets.company': 'Company',
    'telecomAssets.position': 'Position/Activity',
    'telecomAssets.phoneName': 'Phone Name',
    'telecomAssets.activity': 'Activity',
    'telecomAssets.addNewAsset': 'Add New Asset',
    'telecomAssets.editAsset': 'Edit Asset',
    'telecomAssets.assetDetails': 'Asset Details',
    'telecomAssets.updateAsset': 'Update Asset',
    'telecomAssets.close': 'Close',
    'telecomAssets.allProviders': 'All Providers',
    'telecomAssets.allStatus': 'All Status',
    'telecomAssets.of': 'of',
    'telecomAssets.assets': 'assets',
    'telecomAssets.simInformation': 'SIM Information',
    'telecomAssets.organizationDetails': 'Organization Details',
    
    // Device Types
    'deviceTypes.laptop': 'Laptop',
    'deviceTypes.desktop': 'Desktop',
    'deviceTypes.mouse': 'Mouse',
    'deviceTypes.keyboard': 'Keyboard',
    'deviceTypes.headphones': 'Headphones',
    'deviceTypes.monitor': 'Monitor',
    'deviceTypes.server': 'Server',
    'deviceTypes.printer': 'Printer',
    
    // Fields
    'fields.deviceType': 'Device Type',
    'fields.ownerName': 'Owner',
    'fields.department': 'Department',
    'fields.zone': 'Zone/Emplacement',
    'fields.activity': 'Poste/Activité',
    'fields.serialNumber': 'Serial Number',
    'fields.ticketNumber': 'Ticket Number',
    'fields.model': 'Model',
    'fields.brand': 'Brand',
    'fields.date': 'Date',
    'fields.status': 'Status',
    'fields.ram': 'RAM (GB)',
    'fields.disk': 'Disk (GB)',
    'fields.processor': 'Processor',
    'fields.os': 'Operating System',
    'fields.peripheralType': 'Peripheral Type',
    'fields.connectionType': 'Connection Type',
    'fields.location': 'Location',
    'fields.macAddress': 'MAC Address',
    'fields.ipAddress': 'IP Address',
    'fields.purchaseDate': 'Purchase Date',
    'fields.warrantyExpiry': 'Warranty Expiry',
    'fields.notes': 'Notes',
    'fields.deviceName': 'Device Name',
    'fields.type': 'Type',
    'fields.assignedUser': 'Assigned User',
    'fields.manufacturer': 'Manufacturer',
    'fields.lastSeen': 'Last Seen',
    'fields.antivirusStatus': 'Antivirus Status',
    'fields.updateStatus': 'Update Status',
    'fields.year': 'Year',
    'fields.name': 'Name',
    'fields.imei': 'IMEI',
    'fields.storage': 'Storage (GB)',
    'fields.hostname': 'Hostname',
    'fields.company': 'Company',
    'fields.description': 'Description',
    'fields.priority': 'Priority',
    'fields.startDate': 'Start Date',
    'fields.endDate': 'End Date',
    'fields.budget': 'Budget',
    'fields.manager': 'Manager',
    'export.format': 'Export Format',
    'export.theme': 'Theme Style',
    
    // Dashboard
    'dashboard.totalDevices': 'Total Devices',
    'dashboard.totalDevicesSubtitle': 'All registered devices',
    'dashboard.activeDevices': 'Active Devices',
    'dashboard.activeDevicesSubtitle': 'Currently online',
    'dashboard.totalTasks': 'Total Tasks',
    'dashboard.totalTasksSubtitle': 'All assigned tasks',
    'dashboard.completedTasks': 'Completed Tasks',
    'dashboard.completedTasksSubtitle': 'Successfully finished',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.activeProjectsSubtitle': 'Currently in progress',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.totalUsersSubtitle': 'Registered users',
    'dashboard.deviceStatus.active': 'Active',
    'dashboard.deviceStatus.inactive': 'Inactive',
    'dashboard.deviceStatus.maintenance': 'Maintenance',
    'dashboard.charts.cpu': 'CPU %',
    'dashboard.charts.memory': 'Memory %',
    'dashboard.charts.disk': 'Disk %',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.maintenance': 'Maintenance',
    'status.retired': 'Retired',
    
    // AI Import
    'aiImport.title': 'AI Import',
    'aiImport.subtitle': 'Import assets with artificial intelligence',
    'aiImport.selectFile': 'Select File',
    'aiImport.preview': 'Preview',
    'aiImport.import': 'Import',
    'aiImport.success': 'Import successful',
    'aiImport.error': 'Import error',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.clearAll': 'Clear all',
    'notifications.noNotifications': 'No notifications',
    'notifications.markAsRead': 'Mark as read',
    'notifications.delete': 'Delete',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.systemStatus': 'System Status',
    'dashboard.performance': 'Performance',
    'dashboard.storage': 'Storage',
    'dashboard.memory': 'Memory',
    'dashboard.cpu': 'CPU',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your account',
    'login.applicationMode': 'Application Mode',
    'login.changeMode': 'Change Mode',
    'login.current': 'Current',
    'login.modes.local': 'Local',
    'login.modes.client': 'Client',
    'login.modes.server': 'Server',
    'login.modes.cloud': 'Cloud',
    'login.availableServers': 'Available Servers',
    'login.serverName': 'Server Name',
    'login.serverIP': 'Server IP',
    'login.confirmPassword': 'Confirm Password',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.invalidCredentials': 'Invalid credentials',
    'login.loginError': 'Login error',
    'login.enterEmail': 'Enter your email address',
    'login.enterPassword': 'Enter your password',
    
    // Devices
    'devices.title': 'Devices',
    'devices.subtitle': 'Manage your connected devices',
    'devices.addDevice': 'Add Device',
    'devices.deviceName': 'Device Name',
    'devices.deviceType': 'Device Type',
    'devices.status': 'Status',
    'devices.lastSeen': 'Last Seen',
    'devices.actions': 'Actions',
    'devices.noDevices': 'No devices found',
    'devices.addFirstDevice': 'Add first device',
    'devices.searchPlaceholder': 'Search devices...',
    'devices.allTypes': 'All Types',
    'devices.allStatus': 'All Status',
    'devices.online': 'Online',
    'devices.offline': 'Offline',
    'devices.unknown': 'Unknown',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.subtitle': 'Manage your tasks and projects',
    'tasks.addTask': 'Add Task',
    'tasks.taskName': 'Task Name',
    'tasks.description': 'Description',
    'tasks.priority': 'Priority',
    'tasks.status': 'Status',
    'tasks.assignee': 'Assigned To',
    'tasks.dueDate': 'Due Date',
    'tasks.createdDate': 'Created Date',
    'tasks.noTasks': 'No tasks found',
    'tasks.addFirstTask': 'Add first task',
    'tasks.searchPlaceholder': 'Search tasks...',
    'tasks.high': 'High',
    'tasks.medium': 'Medium',
    'tasks.low': 'Low',
    'tasks.todo': 'To Do',
    'tasks.inProgress': 'In Progress',
    'tasks.completed': 'Completed',
    'tasks.cancelled': 'Cancelled',
    
    // Projects
    'projects.title': 'Projects',
    'projects.subtitle': 'Manage your projects',
    'projects.addProject': 'Add Project',
    'projects.projectName': 'Project Name',
    'projects.description': 'Description',
    'projects.status': 'Status',
    'projects.manager': 'Manager',
    'projects.startDate': 'Start Date',
    'projects.endDate': 'End Date',
    'projects.progress': 'Progress',
    'projects.noProjects': 'No projects found',
    'projects.addFirstProject': 'Add first project',
    'projects.searchPlaceholder': 'Search projects...',
    'projects.planning': 'Planning',
    'projects.active': 'Active',
    'projects.completed': 'Completed',
    'projects.onHold': 'On Hold',
    'projects.cancelled': 'Cancelled',
    
    // Users
    'users.title': 'Users',
    'users.subtitle': 'Manage system users',
    'users.addUser': 'Add User',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.role': 'Role',
    'users.department': 'Department',
    'users.status': 'Status',
    'users.lastLogin': 'Last Login',
    'users.createdDate': 'Created Date',
    'users.noUsers': 'No users found',
    'users.addFirstUser': 'Add first user',
    'users.searchPlaceholder': 'Search users...',
    'users.admin': 'Administrator',
    'users.user': 'User',
    'users.manager': 'Manager',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.suspended': 'Suspended',
    
    // System Info
    'system.title': 'System Information',
    'system.subtitle': 'Monitor your system performance',
    'system.overview': 'Overview',
    'system.hardware': 'Hardware',
    'system.software': 'Software',
    'system.network': 'Network',
    'system.storage': 'Storage',
    'system.memory': 'Memory',
    'system.cpu': 'CPU',
    'system.uptime': 'Uptime',
    'system.version': 'Version',
    'system.platform': 'Platform',
    'system.architecture': 'Architecture',
    'system.totalMemory': 'Total Memory',
    'system.freeMemory': 'Free Memory',
    'system.usedMemory': 'Used Memory',
    'system.cpuUsage': 'CPU Usage',
    'system.diskSpace': 'Disk Space',
    'system.networkInterfaces': 'Network Interfaces',
    'system.loadAverage': 'Load Average',
    
    // AI
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Use artificial intelligence to automate your tasks',
    'ai.chat': 'AI Chat',
    'ai.askQuestion': 'Ask a question...',
    'ai.send': 'Send',
    'ai.clear': 'Clear',
    'ai.import': 'AI Import',
    'ai.export': 'AI Export',
    'ai.analyze': 'Analyze',
    'ai.generate': 'Generate',
    'ai.recommendations': 'Recommendations',
    'ai.insights': 'Insights',
    'ai.noData': 'No data available',
    'ai.loading': 'Loading...',
    'ai.error': 'AI Error',
    'ai.success': 'AI Success',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.devices': 'Devices',
    'sidebar.itAssets': 'IT Assets',
    'sidebar.telecomAssets': 'Telecom Assets',
    'sidebar.tasks': 'Tasks',
    'sidebar.projects': 'Projects',
    'sidebar.users': 'Users',
    'sidebar.system': 'System',
    'sidebar.ai': 'AI',
    'sidebar.settings': 'Settings',
    'sidebar.logout': 'Logout',
    
    // Header
    'header.notifications': 'Notifications',
    'header.profile': 'Profile',
    'header.settings': 'Settings',
    'header.help': 'Help',
    'header.support': 'Support',
    
    // Common Actions
    'actions.view': 'View',
    'actions.edit': 'Edit',
    'actions.delete': 'Delete',
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'actions.close': 'Close',
    'actions.back': 'Back',
    'actions.next': 'Next',
    'actions.previous': 'Previous',
    'actions.refresh': 'Refresh',
    'actions.loading': 'Loading...',
    'actions.error': 'Error',
    'actions.success': 'Success',
    'actions.warning': 'Warning',
    'actions.info': 'Information',
    'actions.confirm': 'Confirm',
    'actions.yes': 'Yes',
    'actions.no': 'No',
    'actions.ok': 'OK',
    'actions.apply': 'Apply',
    'actions.reset': 'Reset',
    'actions.submit': 'Submit',
    'actions.upload': 'Upload',
    'actions.download': 'Download',
    'actions.print': 'Print',
    'actions.share': 'Share',
    'actions.copy': 'Copy',
    'actions.paste': 'Paste',
    'actions.cut': 'Cut',
    'actions.undo': 'Undo',
    'actions.redo': 'Redo',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Get saved language from localStorage or default to French
  const getInitialLanguage = (): Language => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'fr';
  };

  const [language, setLanguage] = useState<Language>(getInitialLanguage);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app-language', lang);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
